use tracing::info;
use std::process::Command;
use std::os::windows::process::CommandExt;
use std::path::PathBuf;
use std::fs;

const CREATE_NO_WINDOW: u32 = 0x08000000;

/// Define the elevated task name
pub const TASK_NAME: &str = r#"\WSLDashboard\WSLDashboardTask"#;

/// Get the script storage directory (~/.wsldashboard/scripts)
pub fn get_scripts_dir() -> PathBuf {
    let home_dir = dirs::home_dir().unwrap_or_else(|| PathBuf::from("."));
    home_dir.join(".wsldashboard").join("scripts")
}

/// Get the path for the scheduled task intermediary script
pub fn get_script_path() -> PathBuf {
    get_scripts_dir().join("task_scheduler.ps1")
}

/// Ensure the scheduled task intermediary script exists and its content is correct
pub fn ensure_task_script_exists() -> Result<PathBuf, String> {
    let scripts_dir = get_scripts_dir();
    if !scripts_dir.exists() {
        fs::create_dir_all(&scripts_dir).map_err(|e| format!("Failed to create scripts directory: {}", e))?;
    }

    let exe_path = std::env::current_exe().unwrap_or_else(|_| PathBuf::from("wsldashboard.exe"));
    let exe_str = exe_path.to_string_lossy();
    let script_path = get_script_path();

    let script_content = format!(
        "# Auto-generated by WSL Dashboard for elevated network automation\n\
         $exePath = \"{}\"\n\
         Start-Process -FilePath $exePath -ArgumentList \"/scheduler\" -WindowStyle Hidden -Wait",
        exe_str
    );

    fs::write(&script_path, script_content).map_err(|e| format!("Failed to write task script: {}", e))?;
    Ok(script_path)
}

/// Request UAC authorization to create an elevated scheduled task (RL HIGHEST)
///
/// Uses the verified ShellExecuteEx + run_invisible_elevated_command channel to execute schtasks.
/// /TR points to the .ps1 script so that the path can be silently updated later by modifying the script with normal privileges.
pub fn register_task_with_elevation() -> Result<(), String> {
    let script_path = ensure_task_script_exists()?;
    let script_str = script_path.to_string_lossy();

    // Construct the schtasks /Create command line
    // /TR executes the PowerShell script, using -WindowStyle Hidden to ensure no window is shown
    let tr_value = format!("powershell.exe -ExecutionPolicy Bypass -WindowStyle Hidden -File \"{}\"", script_str);
    let schtasks_cmd = format!(
        "schtasks /Create /TN \"{}\" /TR \"{}\" /SC ONLOGON /RL HIGHEST /F",
        TASK_NAME, tr_value
    );

    info!("Registering scheduled task via elevated schtasks: TN={}, TR={}", TASK_NAME, tr_value);

    // Execute via verified ShellExecuteEx elevation channel (waits synchronously for completion)
    crate::utils::system::run_invisible_elevated_command(&schtasks_cmd)
}

/// Check if the elevated task exists
pub fn check_task_exists() -> bool {
    tracing::debug!("Checking if task exists: {}", TASK_NAME);
    let output = Command::new("schtasks")
        .args(&["/Query", "/TN", TASK_NAME])
        .creation_flags(CREATE_NO_WINDOW)
        .output();
        
    if let Ok(out) = output {
        out.status.success()
    } else {
        false
    }
}

